### ISSUE TITLE
Jitpack download not working

### ISSUE THREAD

**Issue by WolfgangHG** [hantsy/arquillian-glassfish#50]
I try to use your adapter in order to upgrade an old JavaEE8 project to JakartaEE10 and GlassFish 7.

Maven is failing to download your jars from jitpack:

```
Downloading from jitpack.io: https://jitpack.io/com/github/hantsy/arquillian-container-glassfish-jakarta/arquillian-glassfish-managed-jakarta/7.0.12/arquillian-glassfish-managed-jakarta-7.0.12.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/github/hantsy/arquillian-container-glassfish-jakarta/arquillian-glassfish-managed-jakarta/7.0.12/arquillian-glassfish-managed-jakarta-7.0.12.jar

...

[ERROR] dependency: com.github.hantsy.arquillian-container-glassfish-jakarta:arquillian-glassfish-managed-jakarta:jar:7.0.12 (test)
[ERROR]         Could not find artifact com.github.hantsy.arquillian-container-glassfish-jakarta:arquillian-glassfish-managed-jakarta:jar:7.0.12 in jitpack.io (https://jitpack.io)
[ERROR]         Could not find artifact com.github.hantsy.arquillian-container-glassfish-jakarta:arquillian-glassfish-managed-jakarta:jar:7.0.12 in central (https://repo.maven.apache.org/maven2)
```

Entering the URL in a browser also returns errors.

Is it just bad luck and Jitpack has problems, or is it another problem? Or a trivial typo by me?

**Comment by bvfalcon** [comment]
`use <version>v7.0.10</version>`  -- this helps for me because of:
1) tests for 7.0.12 are failed and build was not assembled
2) last successfull build is **v**7.0.10

**Comment by WolfgangHG** [comment]
Thanks for the feedback. But I switched to https://github.com/OmniFish-EE/arquillian-container-glassfish already ;-). I will close this issue.
